# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI

on:
  push:
    branches:
    - main
  schedule: # schedule a regular run if needed
   # Weekly Monday 9AM build
   - cron: "0 9 * * 1"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@99401c364fa51c9c507d3cd6d272049278ac0b2c  # v2.4.0
    with:
      envs: |
        - linux: check-style
        - linux: check-security
        - linux: build-dist
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@99401c364fa51c9c507d3cd6d272049278ac0b2c  # v2.4.0
    with:
      envs: |
        - linux: test-oldestdeps
          python-version: 3.11
        - linux: test
          python-version: 3.13
        - linux: test-alldeps
          python-version: 3.11
        - linux: test-alldeps
          python-version: 3.12
        - linux: test-alldeps
          python-version: 3.13
        - linux: test-alldeps
          python-version: 3.14
        # `tox` may overwrite the `requires-python` version when creating a test environment;
        # if that occurs specify the version in the tox environment e.g., py313-test-alldeps;
        - macos: test-alldeps
          python-version: 3.14
        - linux: test-alldeps-cov
          python-version: 3.14
          coverage: codecov
